[package]
name = "pgbr-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]

[dependencies]
# Source-of-truth list of supported PG major versions.
pgbr-build = { path = "../pgbr-build" }
# Buffer-oriented I/O traits used by the pg_control reader.
pgbr-io = { path = "../pgbr-io" }

[lints]
workspace = true
